name: "test-WF"
on:
  pull_request:
    branches: []
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install pytest
        run: pip install pytest  
      - name: utest
        run: pytest .        
  